define(`HOST_COLOR', ``91'')
define(`CPUS', ``4'')
define(`ALSA_CARD', ``0'')
define(`PRIMARY_MONITOR', ``LVDS-1'')
define(`DEFAULT_LAN_IFACE', ``enp0s25'')
define(`WIFI_IFACE', ``wlp3s0'')
define(`BATTERY', ``0', `1'')
define(`SOUND_SERVER', ``pipewire'')
define(`PERL_LOCAL_LIB', ``false'')
define(`OPAM_IN_PATH', ``false'')
define(`VIM_PACKAGE_LOADER', ``none'')
