define(`HOST_COLOR', ``93'')
define(`CPUS', ``32'')
define(`I3_STATUS_COMMAND', ``i3blocks'')
define(`PRIMARY_MONITOR', ``DP-0'')
define(`CPU_TEMPERATURE_FILE', ``/sys/class/hwmon/hwmon0/temp1_input'')
define(`DEFAULT_LAN_IFACE', ``enp8s0'')
define(`IME_NAME', ``ibus'')
