define(`HOST_COLOR', ``94'')
define(`CPUS', ``4'')
define(`HTTP_PROXY', `')
define(`ALSA_CARD', ``0'')
define(`I3_STATUS_COMMAND', ``i3status'')
define(`PRIMARY_MONITOR', `')
define(`DEFAULT_LAN_IFACE', `enp3s0')
