define(`HOST_COLOR', ``93'')
define(`CPUS', ``6'')
define(`HTTP_PROXY', ``http://127.0.0.1:3128'')
define(`I3_STATUS_COMMAND', ``i3blocks'')
define(`PRIMARY_MONITOR', ``DP-0'')
define(`CPU_TEMPERATURE_FILE', ``/sys/class/hwmon/hwmon0/temp1_input'')
